ShopDienTu/Areas/Admin/Controllers/QuanLyDanhMucController.cs
using AutoMapper;
using ShopDienTu.Infastructure.Core;
using ShopDienTu.Infastructure.Extension;
using ShopDienTu.Model.DAO;
using ShopDienTu.Model.Model;
using ShopDienTu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopDienTu.Areas.Admin.Controllers
{
    [AuthorizeBase(Roles = "QuanTri")]
    public class QuanLyDanhMucController : BaseController
    {
        // GET: Admin/QuanLyDanhMuc
        #region QuanLyDanhMuc
        [Authorize(Roles = "QuanTri")]
        [HttpGet]
        public ActionResult Index()
        {
            var loaiSPDao = new LoaiSanPhamDao();

            var model = loaiSPDao.GetAll();

            var viewModel = Mapper.Map<IEnumerable<LoaiSanPham>, IEnumerable<LoaiSanPhamViewModel>>(model);

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult ThemDanhMuc()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemDanhMuc(LoaiSanPhamViewModel loaiSPViewModel)
        {
            if (ModelState.IsValid)
            {
                var loaiSPDao = new LoaiSanPhamDao();
                var loaiSP = new LoaiSanPham();
                loaiSP.UpdateLoaiSanPham(loaiSPViewModel);
                loaiSPDao.Add(loaiSP);
                return RedirectToAction("Index");
            }
            return View(loaiSPViewModel);
        }

        [HttpGet]
        public ActionResult SuaDanhMuc(int id)
        {
            var loaiSPDao = new LoaiSanPhamDao();

            var loaiSP = loaiSPDao.GetByID(id);

            var loaiSPViewModel = new LoaiSanPhamViewModel();

            loaiSPViewModel.UpdateLoaiSanPham(loaiSP);

            return View(loaiSPViewModel);
        }

        [HttpPost]
        public ActionResult SuaDanhMuc(LoaiSanPhamViewModel loaiSPViewModel)
        {
            if (ModelState.IsValid)
            {
                var loaiSPDao = new LoaiSanPhamDao();

                var loaiSP = new LoaiSanPham();

                loaiSP.UpdateLoaiSanPham(loaiSPViewModel);

                loaiSPDao.Update(loaiSP);

                return RedirectToAction("Index");
            }
            return View(loaiSPViewModel);
        }

        [HttpGet]
        public ActionResult XoaDanhMuc(int id)
        {
            var loaiSPDao = new LoaiSanPhamDao();

            loaiSPDao.Delete(id);

            return RedirectToAction("Index");
        }
        #endregion
    }
}

ShopDienTu/Areas/Admin/Views/QuanLyDanhMuc/Index.cshtml
@model IEnumerable<ShopDienTu.Models.LoaiSanPhamViewModel>

@{
    ViewBag.Title = "DanhSachDanhMuc";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh sách danh mục</h2>
<br><br>
<p>
    @*<a href="@Url.Action("ThemDanhMuc",null,new {@class= "btn-btn succses" })">Thêm danh mục</a>*@
    @Html.ActionLink("Add", "ThemDanhMuc", null, new { @class = "btn btn-success" })
</p>
<br><br>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Mã loại sản phẩm")
        </th>
        <th>
            @Html.DisplayName("Tên loại")
        </th>
        <th>
            @Html.DisplayName("Icon")
        </th>
        <th>
            @Html.DisplayName("Bí danh")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaLoaiSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenLoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Icon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BiDanh)
            </td>
            <td>
                @Html.ActionLink("Update", "SuaDanhMuc", new { id = item.MaLoaiSP }) |
                @Html.ActionLink("Delete", "XoaDanhMuc", new { id = item.MaLoaiSP }, new { @class = "btnDelete", onclick = "return confirm('Bạn có muốn xóa danh mục ?')" })
            </td>
        </tr>
    }

</table>

ShopDienTu/Areas/Admin/Views/QuanLyDanhMuc/SuaDanhMuc.cshtml
@model ShopDienTu.Models.LoaiSanPhamViewModel

@{
    ViewBag.Title = "SuaDanhMuc";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sửa Danh Mục</h2>
<br><br>
@using (Html.BeginForm("SuaDanhMuc", "QuanLyDanhMuc", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaLoaiSP)

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BiDanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BiDanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BiDanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" onclick="return confirm('Bạn có muốn update danh mục ?')" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

ShopDienTu/Areas/Admin/Views/QuanLyDanhMuc/ThemDanhMuc.cshtml
@model ShopDienTu.Models.LoaiSanPhamViewModel

@{
    ViewBag.Title = "ThemDanhMuc";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm Danh Mục</h2>
<br><br>
@using (Html.BeginForm("ThemDanhMuc", "QuanLyDanhMuc", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BiDanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BiDanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BiDanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>