ShopDienTu/Areas/Admin/Controllers/QuanLySanPhamController.cs
using AutoMapper;
using ShopDienTu.Infastructure.Extension;
using ShopDienTu.Model.DAO;
using ShopDienTu.Model.Model;
using ShopDienTu.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using PagedList;
using System;
using ShopDienTu.Infastructure.Core;

namespace ShopDienTu.Areas.Admin.Controllers
{
    [AuthorizeBase(Roles = "QuanTri,QuanLySanPham")]
    public class QuanLySanPhamController : BaseController
    {
        // GET: Admin/QuanLySanPham
        SanPhamDao sanphamDao;
        NhaCungCapDao nhaCCDao;
        LoaiSanPhamDao loaiSPDao;
        NhaSanXuatDao nhaSXDao;


        public QuanLySanPhamController()
        {
            sanphamDao = new SanPhamDao();
            nhaCCDao = new NhaCungCapDao();
            loaiSPDao = new LoaiSanPhamDao();
            nhaSXDao = new NhaSanXuatDao();
        }

        #region QuanLySanPham
        [Authorize(Roles = "QuanTri,QuanLySanPham")]
        public ActionResult Index(int? page)
        {
            int PageSize = 10;

            int PageNumber = (page ?? 1) - 1;

            int totalCount = 0;

            var model = sanphamDao.GetAll(out totalCount).ToPagedList(PageNumber + 1, PageSize);

            var viewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(model);

            IPagedList<SanPhamViewModel> spView = new StaticPagedList<SanPhamViewModel>(viewModel, PageNumber + 1, PageSize, totalCount);

            return View(spView);
        }

        [HttpGet]
        public ActionResult TimKiemSanPham(string sTuKhoa, int? page)
        {

            int PageSize = 10;

            int PageNumber = (page ?? 1) - 1;

            int totalCount = 0;

            if (String.IsNullOrEmpty(sTuKhoa))
            {
                var model = sanphamDao.GetAll(out totalCount).ToPagedList(PageNumber + 1, PageSize);

                var viewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(model);

                IPagedList<SanPhamViewModel> spView = new StaticPagedList<SanPhamViewModel>(viewModel, PageNumber + 1, PageSize, totalCount);

                return PartialView("IndexPartial", spView);
            }
            else
            {
                var model = sanphamDao.Search(sTuKhoa, out totalCount).ToPagedList(PageNumber + 1, PageSize);

                var viewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(model);

                IPagedList<SanPhamViewModel> spView = new StaticPagedList<SanPhamViewModel>(viewModel, PageNumber + 1, PageSize, totalCount);

                ViewBag.TuKhoa = sTuKhoa;

                return PartialView("TimKiemSanPham", spView);
            }

        }

        [HttpGet]
        public ActionResult ThemSanPham()
        {
            ViewBag.MaNCC = new SelectList(nhaCCDao.GetAll(), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(loaiSPDao.GetAll(), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(nhaSXDao.GetAll(), "MaNSX", "TenNSX");
            return View();
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ThemSanPham(SanPhamViewModel spViewModel)
        {

            ViewBag.MaNCC = new SelectList(nhaCCDao.GetAll(), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(loaiSPDao.GetAll(), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(nhaSXDao.GetAll(), "MaNSX", "TenNSX");

            if (ModelState.IsValid)
            {
                spViewModel.NgayCapNhap = DateTime.Now;
                var sanpham = new SanPham();
                sanpham.UpdateSanPham(spViewModel);
                sanphamDao.Add(sanpham);
                SetAlert("Thêm sản phẩm thành công", "success");
                return RedirectToAction("Index");
            }
            SetAlert("Thêm sản phẩm không thành công", "error");
            return View(spViewModel);
        }

        [HttpGet]
        public ActionResult SuaSanPham(int id)
        {
            var sanpham = sanphamDao.GetByID(id);

            var sanphamViewModel = new SanPhamViewModel();

            sanphamViewModel.UpdateSanPham(sanpham);

            ViewBag.MaNCC = new SelectList(nhaCCDao.GetAll(), "MaNCC", "TenNCC", sanpham.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(loaiSPDao.GetAll(), "MaLoaiSP", "TenLoai", sanpham.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(nhaSXDao.GetAll(), "MaNSX", "TenNSX", sanpham.MaNSX);

            return View(sanphamViewModel);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult SuaSanPham(SanPhamViewModel spVM)
        {
            ViewBag.MaNCC = new SelectList(nhaCCDao.GetAll(), "MaNCC", "TenNCC", spVM.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(loaiSPDao.GetAll(), "MaLoaiSP", "TenLoai", spVM.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(nhaSXDao.GetAll(), "MaNSX", "TenNSX", spVM.MaNSX);

            if (ModelState.IsValid)
            {
                spVM.NgayCapNhap = DateTime.Now;

                var sanpham = new SanPham();

                sanpham.UpdateSanPham(spVM);

                sanphamDao.Update(sanpham);

                SetAlert("Sửa sản phẩm thành công", "success");

                return RedirectToAction("Index");
            }
            SetAlert("Sửa sản phẩm không thành công", "error");
            return View(spVM);
        }

        [HttpGet]
        public ActionResult SapHetHang(int ?page)
        {
            int PageSize = 5;

            int PageNumber = (page ?? 1) - 1;

            int totalCount = 0;

            var model = sanphamDao.GetOutOfStock(out totalCount).ToPagedList(PageNumber + 1, PageSize);

            var viewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(model);

            IPagedList<SanPhamViewModel> spView = new StaticPagedList<SanPhamViewModel>(viewModel, PageNumber + 1, PageSize, totalCount);

            return PartialView("SapHetHang", spView);

        }

        [HttpGet]
        public ActionResult XoaSanPham(int id)
        {
            var sanphamDao = new SanPhamDao();

            sanphamDao.Delete(id);

            return RedirectToAction("Index");
        }

        #endregion QuanLySanPham
    }
}

ShopDienTu/Areas/Admin/Views/QuanLySanPham/Index.cshtml
@model PagedList.IPagedList<ShopDienTu.Models.SanPhamViewModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = "DanhSachSanPham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh Sách Sản Phẩm</h2>
<br><br>
<p style="float:left;padding-right:200px">
    @Html.ActionLink("Add", "ThemSanPham", null, new { @class = "btn btn-success" })
    @Ajax.ActionLink("List product out of stock", "SapHetHang", null, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "KetQua", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-success" })
</p>
<p style="margin-top:5px">
    @using (Ajax.BeginForm("TimKiemSanPham", "QuanLySanPham", new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "KetQua", InsertionMode = InsertionMode.Replace }))
    {
        <input type="text" id="txtTimKiem" value="" name="sTuKhoa" placeholder="Nhập vào tên sản phẩm" />
        <input type="submit" value="Search" class="btn btn-primary" />
    }
</p>
<br><br>
<div id="KetQua">

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().TenSP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().HinhAnh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().SoLuongTon)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenSP)
                </td>
                <td>
                    <img src="@item.HinhAnh" alt="@item.TenSP" style="width:150px;height:100px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuongTon)
                </td>
                <td>
                    @Html.ActionLink("Update", "SuaSanPham", new { id = item.MaSP }) |
                    @Html.ActionLink("Delete", "XoaSanPham", new { id = item.MaSP }, new { @class = "btnDelete", onclick = "return confirm('Bạn có muốn xóa san pham ?')" })
                </td>
            </tr>
        }
    </table>
    <div class="dlink">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("TimKiemSanPham", new { page = page }),
        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "KetQua", InsertionMode = InsertionMode.Replace }))
    </div>

</div>

ShopDienTu/Areas/Admin/Views/QuanLySanPham/SuaSanPham.cshtml
@using System.Web.Script.Serialization;
@model ShopDienTu.Models.SanPhamViewModel

@{
    ViewBag.Title = "SuaSanPham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    var img = new JavaScriptSerializer().Deserialize<List<string>>(Model.HinhAnh1);
}

<h2>SuaSanPham</h2>
<br><br>
@section jsFooter{
    <script>
        var arrImg = @Html.Raw(Model.HinhAnh1);
        var editor = CKEDITOR.replace('txtMoTa', {
            customConfig: '/Assets/Admin/js/plugins/ckeditor/config.js'
        });
        var editor1 = CKEDITOR.replace('txtCauHinh', {
            customConfig: '/Assets/Admin/js/plugins/ckeditor/config.js'
        });
        $(document).ready(function () {

            var dongia = formatCurrency(@Model.DonGia);

            $('#tempDonGia').attr('value', dongia);

            $('#btnSelectImage').on('click', function (e) {
                e.preventDefault();
                var finder = new CKFinder();
                finder.selectActionFunction = function (url) {
                    $('#imgHinhAnh').prop({ src: url, style: "width:150px;height:150px" });
                    $('#txtHinhAnh').val(url);
                }
                finder.popup();
            })
            $('#btnSelectImage1').on('click', function (e) {
                e.preventDefault();
                var finder = new CKFinder();
                finder.selectActionFunction = function (url) {
                    //$('#imgHinhAnh').prop({ src: url, style: "width:150px;height:150px" });
                    $('#imgGroup').append(
                       $('<img />').attr({ // Same, create the element and specify its attributes
                           'src': url,
                           'width': '150px',
                           'height': '100px'
                       })
                   )
                    arrImg.push(url);
                }
                finder.popup();
            })
            $('#btnSubmit').on('click', function () {
                $('#imgGroup').append(
                       $('<input />').attr({ // Same, create the element and specify its attributes
                           'value': JSON.stringify(arrImg),
                           'name': 'HinhAnh1'
                       })
                )
                dongia = $('#tempDonGia').val();
                dongia = dongia.replace(/\$|\,/g, '');
                $('#txtDonGia').attr('value', dongia);
            })
        })
    </script>


    <script src="~/Assets/Admin/js/common/formatCurrency.js"></script>
}
@using (Html.BeginForm("SuaSanPham", "QuanLySanPham", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSP)
        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="text" class="form-control" id="tempDonGia" value="" onkeyup="FormatNumber(this)" />
                @Html.HiddenFor(model => model.DonGia, new { htmlAttributes = new { @type = "number" }, id = "txtDonGia" })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CauHinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CauHinh, new { htmlAttributes = new { @class = "form-control" }, id = "txtCauHinh" })
                @Html.ValidationMessageFor(model => model.CauHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" }, id = "txtMoTa" })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input readonly type="number" value="@Model.SoLuongTon" name="SoLuongTon" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Model.HinhAnh" id="imgHinhAnh" style="width:150px;height:100px" />
                <input type="hidden" name="HinhAnh" id="txtHinhAnh" value="@Model.HinhAnh" />
                <br />
                <button id="btnSelectImage">Chọn ảnh</button>
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="imgGroup">
                    @foreach (var imgs in img)
                    {
                        <img src="@imgs" id="imgHinhAnh" style="width:150px;height:100px" />
                    }
                </div>
                <br />
                <button id="btnSelectImage1">Chọn ảnh</button>
                @Html.ValidationMessageFor(model => model.HinhAnh1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNSX", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSP", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(m => m.Moi, new { @checked = "checked" })
                @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Home, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(m => m.Home, new { @checked = "checked" })
                @Html.ValidationMessageFor(model => model.Home, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaXoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(m => m.DaXoa)
                @Html.ValidationMessageFor(model => model.DaXoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" id="btnSubmit" onclick="return confirm('Bạn có muốn sua san pham ?')" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>

ShopDienTu/Areas/Admin/Views/QuanLySanPham/ThemSanPham.cshtml
@using System.Collections.Generic
@model ShopDienTu.Models.SanPhamViewModel

@{
    ViewBag.Title = "ThemSanPham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm Sản Phẩm</h2>
<br><br>
@section jsFooter{
    <script>
        var arrImg = [];

        var editor = CKEDITOR.replace('txtMoTa', {
            customConfig: '/Assets/Admin/js/plugins/ckeditor/config.js'
        });
        var editor1 = CKEDITOR.replace('txtCauHinh', {
            customConfig: '/Assets/Admin/js/plugins/ckeditor/config.js'
        });
        $(document).ready(function () {
            $('#btnSelectImage').on('click', function (e) {
                e.preventDefault();
                var finder = new CKFinder();
                finder.selectActionFunction = function (url) {
                    $('#imgHinhAnh').prop({ src: url, style: "width:150px;height:100px" });
                    $('#txtHinhAnh').val(url);
                }
                finder.popup();
            })
            $('#btnSelectImage1').on('click', function (e) {
                e.preventDefault();
                var finder = new CKFinder();
                finder.selectActionFunction = function (url) {
                    //$('#imgHinhAnh').prop({ src: url, style: "width:150px;height:150px" });
                    $('#imgGroup').append(
                       $('<img />').attr({ // Same, create the element and specify its attributes
                           'src': url,
                           'width': '150px',
                           'height': '100px'
                       })
                   )
                    arrImg.push(url);
                }
                finder.popup();
            })
            $('#btnSubmit').on('click', function () {
                $('#imgGroup').append(
                       $('<input />').attr({ // Same, create the element and specify its attributes
                           'value': JSON.stringify(arrImg),
                           'name': 'HinhAnh1'
                       })
                )

                var dongia = $('#tempDonGia').val();
                var dongia = dongia.replace(/\$|\,/g, '');
                $('#txtDonGia').attr('value', dongia);
            })
        })
    </script>


    <script src="~/Assets/Admin/js/common/formatCurrency.js"></script>
}

@using (Html.BeginForm("ThemSanPham", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" }, id = "txtTen" })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.Editor("Đơn giá", new { htmlAttributes = new { @class = "form-control", @onkeyup = "FormatNumber(this)" },id="tempDonGia"})*@
                @*@Html.Editor("hihi",new { htmlAttributes = new { @class = "form-control",@type="number"},id="tempDonGia"})*@
                <input type="text" class="form-control" id="tempDonGia" value="" onkeyup="FormatNumber(this)" />
                @Html.HiddenFor(model => model.DonGia, new { htmlAttributes = new { @type = "number" }, id = "txtDonGia" })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CauHinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CauHinh, new { htmlAttributes = new { @class = "form-control" }, id = "txtCauHinh" })
                @Html.ValidationMessageFor(model => model.CauHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" }, id = "txtMoTa" })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="" id="imgHinhAnh" />
                <input type="hidden" name="HinhAnh" id="txtHinhAnh" />
                <br />
                <button id="btnSelectImage">Chọn ảnh</button>
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="imgGroup">
                </div>
                <br />
                <button id="btnSelectImage1">Chọn ảnh</button>
                @Html.ValidationMessageFor(model => model.HinhAnh1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNSX", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSP", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(m => m.Moi, new { @checked = "checked" })
                @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Home, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(m => m.Home, new { @checked = "checked" })
                @Html.ValidationMessageFor(model => model.Home, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaXoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(m => m.DaXoa)
                @Html.ValidationMessageFor(model => model.DaXoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" id="btnSubmit" onclick="return confirm('Bạn có muốn them san pham ?')" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>