ShopDienTu/Models/SanPhamViewModel.cs
using ShopDienTu.Model.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShopDienTu.Models
{
    public class SanPhamViewModel
    {
        [Key]
        [DisplayName("Mã sản phẩm")]
        public int MaSP { get; set; }

        [DisplayName("Tên sản phẩm")]
        public string TenSP { get; set; }

        [DisplayName("Đơn giá")]
        public decimal DonGia { get; set; }

        [DisplayName("Ngày cập nhập")]
        public DateTime? NgayCapNhap { get; set; }

        [DisplayName("Cấu hình")]
        public string CauHinh { get; set; }

        [DisplayName("Mô tả")]
        public string MoTa { get; set; }

        [DisplayName("Hình ảnh")]
        public string HinhAnh { get; set; }

        [DisplayName("Số lượng tồn")]
        public int? SoLuongTon { get; set; }

        [DisplayName("Lượt xem")]
        public int? LuotXem { get; set; }

        [DisplayName("Lượt bình chọn")]
        public int? LuotBinhChon { get; set; }

        [DisplayName("Lượt bình luận")]
        public int? LuotBinhLuan { get; set; }

        [DisplayName("Số lần mua")]
        public int? SoLanMua { get; set; }

        [DisplayName("Mới")]
        public bool Moi { get; set; }

        [DisplayName("Tên nhà cung cấp")]
        public int? MaNCC { get; set; }

        [DisplayName("Tên nhà sản xuất")]
        public int? MaNSX { get; set; }

        [DisplayName("Tên loại sản phẩm")]
        public int? MaLoaiSP { get; set; }

        [DisplayName("Ẩn")]
        public bool DaXoa { get; set; }

        [DisplayName("Hiển thị trang chủ")]
        public bool Home { get; set; }

        public string HinhAnh1 { get; set; }

        public virtual NhaSanXuat NhaSanXuat { get; set; }

        public virtual LoaiSanPham LoaiSanPham { get; set; }

    }
}

ShopDienTu/Controllers/SanPhamController.cs
using AutoMapper;
using ShopDienTu.Infastructure.Core;
using ShopDienTu.Infastructure.Extension;
using ShopDienTu.Model.DAO;
using ShopDienTu.Model.Model;
using ShopDienTu.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using PagedList;
using Microsoft.Ajax.Utilities;

namespace ShopDienTu.Controllers
{
    public class SanPhamController : BaseController
    {
        private SanPhamDao spDao;

        public SanPhamController()
        {
            spDao = new SanPhamDao();
        }

        public ActionResult Index(int id, int flag = 1, int page= 1, string sort="")
        {
            int PageSize = 6;
            int totalCount = 0;
            int PageNumber = page - 1; 

            var model = spDao.GetSortListByID(id, out totalCount,sort, page, PageSize).ToPagedList(PageNumber+1, PageSize);

            var viewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(model);

            IPagedList<SanPhamViewModel> spView = new StaticPagedList<SanPhamViewModel>(viewModel, PageNumber+1, PageSize, totalCount);

            ViewBag.ID = id;

            ViewBag.Page = PageNumber + 1;

            ViewBag.Sort = sort;

            if (page == 1 && flag == 1)
            {
                return View(spView);
            }

            return PartialView("IndexPartial", spView);

        }

        public ActionResult Search(string keyword,int flag = 1,int page = 1)
        {
            if (string.IsNullOrEmpty(keyword))
            {
                return RedirectToAction("Index", "HomePage");
            }

            int PageSize = 6;
            int totalCount = 0;
            int PageNumber = page - 1;

            var model = spDao.Search(keyword, out totalCount).ToPagedList(PageNumber + 1, PageSize);
            var viewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(model);

            ViewBag.Keyword = keyword;

            ViewBag.TotalCount = totalCount;

            IPagedList<SanPhamViewModel> spView = new StaticPagedList<SanPhamViewModel>(viewModel, PageNumber + 1, PageSize, totalCount);

            if (page == 1 && flag == 1)
            {
                return View(spView);
            }
            return PartialView("SearchPartial", spView);
        }

        public JsonResult GetListProductByName(string keyword)
        {
            var model = spDao.GetListProductByName(keyword);
            //var viewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(model);
            List<Dictionary<string, string>> listJson = new List<Dictionary<string, string>>();
            foreach (var item in model)
            {
                Dictionary<string, string> dataJson = new Dictionary<string, string>();
                dataJson["TenSP"] = item.TenSP;
                dataJson["HinhAnh"] = item.HinhAnh;
                dataJson["MaSP"] = item.MaSP.ToString();
                dataJson["TenNSX"] = item.NhaSanXuat.TenNSX;
                listJson.Add(dataJson);
            }
            return Json(new
            {
                data = listJson
            }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Detail(int id)
        {
            var spModel = spDao.GetByID(id);
            if (spModel == null)
            {
                return HttpNotFound();
            }
            var spViewModel = new SanPhamViewModel();

            spViewModel.UpdateSanPham(spModel);

            List<string> lstImage = new JavaScriptSerializer().Deserialize<List<string>>(spViewModel.HinhAnh1);

            ViewBag.MoreImage = lstImage;

            var lstRelated = spDao.GetRelated(spViewModel.MaLoaiSP, spViewModel.MaNSX, 6);

            var lstRelatedViewModel = Mapper.Map<IEnumerable<SanPham>, IEnumerable<SanPhamViewModel>>(lstRelated);

            ViewBag.RelatedProduct = lstRelatedViewModel;

            return View(spViewModel);
        }
    }
}

ShopDienTu/Views/SanPham/Detail.cshtml
@model ShopDienTu.Models.SanPhamViewModel
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
    var lstRelatedProduct = ViewBag.RelatedProduct as IEnumerable<ShopDienTu.Models.SanPhamViewModel>;
}
<ul class="breadcrumb">
    <li><a href="/">Trang chủ</a> <span class="divider">/</span></li>
    <li><a href="/san-pham-@Model.NhaSanXuat.MaNSX">Sản phẩm</a> <span class="divider">/</span></li>
    <li class="active">Thông tin sản phẩm</li>
</ul>
<div class="row">
    <div id="gallery" class="span3">
        <a href="@Model.HinhAnh" title=@Model.TenSP>
            <img src="@Model.HinhAnh" style="width:280px;height:200px" alt="@Model.TenSP">
        </a>
        <div id="differentview" class="moreOptopm carousel slide">
            <div class="carousel-inner">
                <div class="item active">
                    @{
                        var moreImage = (List<string>)ViewBag.MoreImage;
                        for (var i = 0; i < 3; i++)
                        {
                            <a href="@moreImage[i]"> <img style="width:30%" src="@moreImage[i]" alt=""></a>
                        }
                    }
                </div>
                <div class="item" style="display:none">
                    @{
                        for (var j = 3; j < moreImage.Count; j++)
                        {
                            <a href="@moreImage[j]"> <img style="width:29%" src="@moreImage[j]" alt=""></a>
                        }
                    }
                </div>
            </div>

            @*<a class="left carousel-control" href="#mycarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#mycarousel" data-slide="next">›</a>*@

        </div>


    </div>
    <div class="span6">
        <h3>@Model.TenSP</h3>
        <hr class="soft">
        <form class="form-horizontal qtyFrm">
            <div class="control-group">
                <label class="control-label"><span>@Model.DonGia.ToString("N0") VND</span></label>
                <div class="controls">
                    <a href="@Url.Action("AddCart","Cart",new {@MaSP = Model.MaSP,@strUrl = Request.Url.ToString() })" class="btn btn-large btn-primary pull-right"> Thêm vào <i class="icon-shopping-cart"></i></a>
                </div>
            </div>
        </form>

        <hr class="soft">
        <h4>@Model.SoLuongTon sản phẩm trong kho</h4>
        <hr class="soft clr">
        @*<p>
                <h2>Thông tin cấu hình</h2>
                @Html.Raw(@Model.CauHinh)
            </p>
            <a class="btn btn-small pull-right" href="#detail">More Details</a>
            <br class="clr">
            <a href="#" name="detail"></a>
            <hr class="soft">*@
    </div>

    <div class="span9">
        <ul id="productDetail" class="nav nav-tabs">
            <li class="active"><a href="#detail" data-toggle="tab">Thông số kỹ thuật</a></li>
            <li><a href="#info" data-toggle="tab">Đánh giá</a></li>
            <li><a href="#related" data-toggle="tab">Sản phẩm liên quan</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="detail">
                @Html.Raw(Model.CauHinh)
            </div>
            <div class="tab-pane fade" id="related">
                <div id="myTab" class="pull-right">
                    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
                    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
                </div>
                <br class="clr">
                <hr class="soft">
                <div class="tab-content">
                    <div class="tab-pane" id="listView">
                        @foreach (var product in lstRelatedProduct)
                        {
                            var url = "/chi-tiet-san-pham-" + product.NhaSanXuat.TenNSX + "-" + product.MaSP;
                            <div class="row">
                                <div class="span2">
                                    <img src="@product.HinhAnh" alt="@product.TenSP">
                                </div>
                                <div class="span4">
                                    <h3>@product.TenSP</h3>
                                    <hr class="soft">

                                    <a class="btn btn-small pull-right" href="@url">View Details</a>
                                    <br class="clr">
                                </div>
                                <div class="span3 alignR">
                                    <form class="form-horizontal qtyFrm">
                                        <h3>@product.DonGia.ToString("N0") VND</h3>
                                        <div class="btn-group">
                                            <a href="@url" class="btn btn-large btn-primary"> Thêm vào <i class="icon-shopping-cart"></i></a>
                                            <a href="@url" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <hr class="soft">
                        }
                    </div>
                    <div class="tab-pane active" id="blockView">
                        <ul class="thumbnails">
                            @foreach (var product in lstRelatedProduct)
                            {
                                var url = "/chi-tiet-san-pham-" + product.NhaSanXuat.TenNSX + "-" + product.MaSP;
                                <li class="span3">
                                    <div class="thumbnail">
                                        <a href="@url"><img src="@product.HinhAnh" alt="@product.TenSP"></a>
                                        <div class="caption">
                                            <h5>@product.TenSP</h5>
                                            <h4 style="text-align:center"><a class="btn" href="@url"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a><br> <a class="btn btn-primary" href="#">@product.DonGia.ToString("N0")</a></h4>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                        <hr class="soft">
                    </div>
                </div>
                <br class="clr">
            </div>
            <div class="tab-pane fade" id="info">
                <h3>Đặc điểm nổi bật của @Model.TenSP</h3>
                @Html.Raw(Model.MoTa)
            </div>
        </div>
    </div>

</div>

ShopDienTu/Views/SanPham/Index.cshtml
@model PagedList.IPagedList<ShopDienTu.Models.SanPhamViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<script type="text/javascript">
    function handleSelect(elm) {
        //window.location = elm.value;
        $.ajax({
            type: 'GET',
            data: {
                page : @ViewBag.Page,
                sort : elm.value,
                flag : 2
            },
            url:'@Url.Action("Index","SanPham")',
            success: function (ketqua) {
                $('#KetQua').html(ketqua);
            }
        });
        document.getElementById("selectbox").value = elm.value;
    }
</script>


<div class="span9">
    <ul class="breadcrumb">
        <li><a href="/">Trang chủ</a> <span class="divider">/</span></li>
        <li class="active">Sản phẩm</li>
    </ul>
    <h3><small class="pull-right"> Có @Model.Count sản phẩm </small></h3>
    <hr class="soft">
    <hr class="soft">

    <form class="form-horizontal span6">
        <div class="control-group">
            <label class="control-label alignL">Sắp xếp </label>
            <select id="selectbox" name="formal" onchange="javascript:handleSelect(this)">
                <option>Lựa chọn</option>
                <option value="name">Tên sản phẩm A->Z</option>
                <option value="new">Mới</option>
                <option value="price">Giá: Thấp->Cao</option>
                <option value="popular">Phổ biến</option>
            </select>
        </div>
    </form>
    <div id="KetQua">
        <div id="myTab" class="pull-right">
            <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
            <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
        </div>
        <br class="clr">
        <div class="tab-content">
            <div class="tab-pane" id="listView">
                @foreach (var item in Model)
                {
                    var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
                    <div class="row">
                        <div class="span2">
                            <img src="@item.HinhAnh" al alt="@item.TenSP">
                            >
                        </div>
                        <div class="span4">
                            <h3>@item.TenSP</h3>
                            <hr class="soft">

                            <a class="btn btn-small pull-right" href="@url">View Details</a>
                            <br class="clr">
                        </div>
                        <div class="span3 alignR">
                            <form class="form-horizontal qtyFrm">
                                <h3>@item.DonGia.ToString("N0") VND</h3>
                                <div class="btn-group">
                                    <a href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = Request.Url.ToString() })" class="btn btn-large btn-primary"> Thêm vào <i class="icon-shopping-cart"></i></a>
                                    <a href="@url" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <hr class="soft">
                }
            </div>
            <div class="tab-pane active" id="blockView">
                <ul class="thumbnails">
                    @foreach (var item in Model)
                    {
                        var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="@url"><img src="@item.HinhAnh" alt="@item.TenSP"></a>
                                <div class="caption">
                                    <h5>@item.TenSP</h5>
                                    <h4 style="text-align:center"><a class="btn" href="@url"> <i class="icon-zoom-in"></i></a> <a class="btn" href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = Request.Url.ToString() })">Thêm vào <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">@item.DonGia.ToString("N0")</a></h4>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
                <hr class="soft">
            </div>
        </div>
        <div class="pagination">
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Index", "SanPham", new { page = page, flag = 2, sort = ViewBag.Sort }),
            PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "KetQua", InsertionMode = InsertionMode.Replace }))
        </div>

    </div>
</div>

ShopDienTu/Views/SanPham/IndexPartial.cshtml
@model PagedList.IPagedList<ShopDienTu.Models.SanPhamViewModel>
@using PagedList.Mvc;


<div id="myTab" class="pull-right">
    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
</div>
<br class="clr">
<div class="tab-content">
    <div class="tab-pane" id="listView">
        @foreach (var item in Model)
            {
                var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
            <div class="row">
                <div class="span2">
                    <img src="@item.HinhAnh" al alt="@item.TenSP">
                    >
                </div>
                <div class="span4">
                    <h3>@item.TenSP</h3>
                    <hr class="soft">

                    <a class="btn btn-small pull-right" href="@url">View Details</a>
                    <br class="clr">
                </div>
                <div class="span3 alignR">
                    <form class="form-horizontal qtyFrm">
                        <h3>@item.DonGia.ToString("N0") VND</h3>
                        <div class="btn-group">
                            <a href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = "http://" + Request.Url.Host + ":" + Request.Url.Port + "/san-pham-" + item.MaNSX })" class="btn btn-large btn-primary"> Thêm vào <i class="icon-shopping-cart"></i></a>
                            <a href="@url" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                        </div>
                    </form>
                </div>
            </div>
                <hr class="soft">
        }
    </div>
    <div class="tab-pane active" id="blockView">
        <ul class="thumbnails">
            @foreach (var item in Model)
            {
                var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
                <li class="span3">
                    <div class="thumbnail">
                        <a href="@url"><img src="@item.HinhAnh" alt="@item.TenSP"></a>
                        <div class="caption">
                            <h5>@item.TenSP</h5>
                            <h4 style="text-align:center"><a class="btn" href="@url"> <i class="icon-zoom-in"></i></a> <a class="btn" href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = "http://" + Request.Url.Host + ":" + Request.Url.Port + "/san-pham-" + item.MaNSX})">Thêm vào <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">@item.DonGia.ToString("N0")</a></h4>
                        </div>
                    </div>
                </li>
            }
        </ul>
        <hr class="soft">
    </div>
</div>
<div class="pagination">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", "SanPham", new { page = page, flag = 2, sort = ViewBag.Sort }),
            PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "KetQua", InsertionMode = InsertionMode.Replace }))
</div>

ShopDienTu/Views/SanPham/Search.cshtml
@model PagedList.IPagedList<ShopDienTu.Models.SanPhamViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="span9">
    <ul class="breadcrumb">
        <li><a href="/">Trang chủ</a> <span class="divider">/</span></li>
        <li class="active">Sản phẩm</li>
    </ul>
    <h3><small class="pull-right"> Có @ViewBag.TotalCount sản phẩm </small></h3>
    <hr class="soft">
    <hr class="soft">
    
    <div id="KetQua">
        <div id="myTab" class="pull-right">
            <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
            <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
        </div>
        <br class="clr">

        <div class="tab-content">
            <div class="tab-pane" id="listView">
                @foreach (var item in Model)
                {
                    var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
                    <div class="row">
                        <div class="span2">
                            <img src="@item.HinhAnh" al alt="@item.TenSP">
                            >
                        </div>
                        <div class="span4">
                            <h3>@item.TenSP</h3>
                            <hr class="soft">

                            <a class="btn btn-small pull-right" href="@url">View Details</a>
                            <br class="clr">
                        </div>
                        <div class="span3 alignR">
                            <form class="form-horizontal qtyFrm">
                                <h3>@item.DonGia.ToString("N0") VND</h3>
                                <div class="btn-group">
                                    <a href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = "http://" + Request.Url.Host + ":" + Request.Url.Port + "/san-pham-" + item.MaNSX })" class="btn btn-large btn-primary"> Thêm vào <i class="icon-shopping-cart"></i></a>
                                    <a href="@url" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <hr class="soft">
                }
            </div>
            <div class="tab-pane active" id="blockView">
                <ul class="thumbnails">
                    @foreach (var item in Model)
                    {
                        var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="@url"><img src="@item.HinhAnh" alt="@item.TenSP"></a>
                                <div class="caption">
                                    <h5>@item.TenSP</h5>
                                    <h4 style="text-align:center"><a class="btn" href="@url"> <i class="icon-zoom-in"></i></a> <a class="btn" href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = "http://" + Request.Url.Host + ":" + Request.Url.Port + "/san-pham-" + item.MaNSX  })">Thêm vào <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">@item.DonGia.ToString("N0")</a></h4>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
                <hr class="soft">
            </div>
        </div>
        <div class="pagination">
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Search", "SanPham", new { page = page, flag = 2, keyword = ViewBag.Keyword }),
            PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "KetQua", InsertionMode = InsertionMode.Replace }))
        </div>
    </div>
</div>

ShopDienTu/Views/SanPham/SearchPartial.cshtml
@model PagedList.IPagedList<ShopDienTu.Models.SanPhamViewModel>
@using PagedList.Mvc;

<div id="myTab" class="pull-right">
    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
</div>
<br class="clr">

<div class="tab-content">
    <div class="tab-pane" id="listView">
        @foreach (var item in Model)
        {
            var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
            <div class="row">
                <div class="span2">
                    <img src="@item.HinhAnh" al alt="@item.TenSP">
                    >
                </div>
                <div class="span4">
                    <h3>@item.TenSP</h3>
                    <hr class="soft">

                    <a class="btn btn-small pull-right" href="@url">View Details</a>
                    <br class="clr">
                </div>
                <div class="span3 alignR">
                    <form class="form-horizontal qtyFrm">
                        <h3>@item.DonGia.ToString("N0") VND</h3>
                        <div class="btn-group">
                            <a href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = "http://" + Request.Url.Host + ":" + Request.Url.Port + "/san-pham-" + item.MaNSX })" class="btn btn-large btn-primary"> Thêm vào <i class="icon-shopping-cart"></i></a>
                            <a href="@url" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                        </div>
                    </form>
                </div>
            </div>
                    <hr class="soft">
        }
    </div>
    <div class="tab-pane active" id="blockView">
        <ul class="thumbnails">
            @foreach (var item in Model)
            {
                var url = "/chi-tiet-san-pham-" + item.NhaSanXuat.TenNSX + "-" + item.MaSP;
                <li class="span3">
                    <div class="thumbnail">
                        <a href="@url"><img src="@item.HinhAnh" alt="@item.TenSP"></a>
                        <div class="caption">
                            <h5>@item.TenSP</h5>
                            <h4 style="text-align:center"><a class="btn" href="@url"> <i class="icon-zoom-in"></i></a> <a class="btn" href="@Url.Action("AddCart","Cart",new {@MaSP = item.MaSP,@strUrl = "http://" + Request.Url.Host + ":" + Request.Url.Port + "/san-pham-" + item.MaNSX })">Thêm vào <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">@item.DonGia.ToString("N0")</a></h4>
                        </div>
                    </div>
                </li>
            }
        </ul>
        <hr class="soft">
    </div>
</div>
<div class="pagination">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Search", "SanPham", new { page = page, flag = 2, keyword = ViewBag.Keyword }),
            PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "KetQua", InsertionMode = InsertionMode.Replace }))
</div>