ShopDienTu/Areas/Admin/Controllers/DangNhapController.cs
using ShopDienTu.Areas.Admin.Models;
using ShopDienTu.Common;
using ShopDienTu.Infastructure.Core;
using ShopDienTu.Model.DAO;
using ShopDienTu.Model.Model;
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ShopDienTu.Areas.Admin.Controllers
{
    public class DangNhapController : Controller
    {
        private ThanhVienDao thanhVienDao;
        private LoaiThanhVienQuyenDao loatTVQuyenDao;

        public DangNhapController()
        {
            thanhVienDao = new ThanhVienDao();
            loatTVQuyenDao = new LoaiThanhVienQuyenDao();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                var result = thanhVienDao.DangNhap(loginModel.TaiKhoan,Encryptor.MD5Hash(loginModel.MatKhau), true);
                if (result == 1)
                {
                    var tv = thanhVienDao.GetUserByTK(loginModel.TaiKhoan, Encryptor.MD5Hash(loginModel.MatKhau));
                    var lstQuyen = loatTVQuyenDao.GetListByID(tv.MaLoaiTV);

                    string quyen = "";
                    foreach (var item in lstQuyen)
                    {
                        quyen += item.Quyen.MaQuyen + ",";
                    }
                    if (!string.IsNullOrEmpty(quyen))
                    {
                        quyen = quyen.Substring(0, quyen.Length - 1);
                    }
                    PhanQuyen(tv.TaiKhoan.ToString(), quyen);
                    var adminSession = new UserLogin();
                    adminSession.UserID = tv.MaThanhVien;
                    adminSession.UserName = tv.TaiKhoan;
                    adminSession.Name = tv.HoTen;
                    Session.Add(CommonConstants.ADMIN_SESSION, adminSession);
                    return RedirectToAction("Index", "Home");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Bạn không có quyền đăng nhập.");
                }
            }

            return View(loginModel);
        }

        public void PhanQuyen(string TaiKhoan, string Quyen)
        {
            FormsAuthentication.Initialize();

            var ticket = new FormsAuthenticationTicket(1,
                TaiKhoan, //user
                DateTime.Now, //timeput
                DateTime.Now.AddHours(3),
                false, //remember
                Quyen, //permission
                FormsAuthentication.FormsCookiePath);

            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
            if (ticket.IsPersistent) cookie.Expires = ticket.Expiration;
            Response.Cookies.Add(cookie);
        }

        public ActionResult DangXuat()
        {
            Session[CommonConstants.ADMIN_SESSION] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

ShopDienTu/Areas/Admin/Views/DangNhap/Index.cshtml
@model ShopDienTu.Areas.Admin.Models.LoginModel
<html>
<head>
    <meta charset="UTF-8">
    <title>Login form shake effect</title>


    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
    <link href="~/Assets/Admin/css/style1.css" rel="stylesheet" />
</head>
<body>
    <h1>Hoài Vương Shop</h1>
    <div class="login-form">
        @using (Html.BeginForm("Index", "DangNhap", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-group ">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <input type="text" class="form-control" placeholder="Tài khoản " name="TaiKhoan">
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                <i class="fa fa-user"></i>
            </div>
            <div class="form-group log-status">
                <input type="password" class="form-control" placeholder="Mật khẩu" name="MatKhau">
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                <i class="fa fa-lock"></i>
            </div>
            <h3 style="font-weight:bold;color:red;text-align:left" id="ThongBao"></h3>
            <a class="link" href="#">Lost your password?</a>
                <button type="submit" class="log-btn">Đăng nhập</button>

        }
    </div>

    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    @*<script src="~/Assets/Admin/js/jquery.unobtrusive-ajax.js"></script>*@
    @*<script src="~/Assets/Admin/js/index.js"></script>*@
</body>
</html>